### PR TITLE
Responsive grid sizing

### PR DESCRIPTION
**Pull request by ELowry**
- Added "Responsive" option to the grid sizing settings.
- Fixed an issue where at 640px window width or lower, the grid would be shifted by an unused `:before` pseudo-element.

### CODE REVIEW

**Comment by ChristopherKlay** [comment]
> Fixed an issue where at 640px window width or lower, the grid would be shifted by an unused :before pseudo-element.

I'm actually aware of said element - i simply didn't remove it because the Stadia website itself is having issues in different spots at anything below 640px width to begin with - i.e. the "Play next" elements at the top of the homescreen that also get shifted around. The extension is mostly aimed at 720p and above, otherwise the effort of fitting the UI on each update of Googles side, would very quickly outweigh the work on the actual extension. I will hide the shop elements (dropdown/searchbar) on screens between 480p and 1080p however, to support everything over 480p, since that's a very easy and consistent fix.

> Added "Responsive" option to the grid sizing settings.

That.. definitely didn't work how you wanted it to work. :p

You change the grid column span of game tiles when entering the responsive case, but you never actually revert that change when switching to other options. Thus you very quickly result in this after switching to "Responsive" and then to "5";

Just changing the grid columns itself, like the current implementation does, i.e.;
```
enhanced_addGlobalStyle(`.lEPylf.YOW9Fd { grid-template-columns: repeat(12,minmax(auto,7.8125rem)) !important; }
                @media (min-width: 1280px) { .lEPylf.YOW9Fd { grid-template-columns: repeat(18,minmax(auto,7.8125rem)) !important; } }
                @media (min-width: 1920px) { .lEPylf.YOW9Fd { grid-template-columns: repeat(24,minmax(auto,7.8125rem)) !important; } }
                @media (min-width: 2560px) { .lEPylf.YOW9Fd { grid-template-columns: repeat(30,minmax(auto,7.8125rem)) !important; } }
                @media (min-width: 3840px) { .lEPylf.YOW9Fd { grid-template-columns: repeat(36,minmax(auto,7.8125rem)) !important; } }`);
```
Works fine however. It isn't the cleanest solution (i'll be honest, having to inject CSS like this itself isn't) but due to !important marked entries overwriting other ones it works comparable to the current solution for other options.

That being said, I honestly never even thought about it in the first place. It'll be implemented in the dev version and then updated here on GitHub when the update is available.

I currently just prefer to have a dev version where i implement changes myself to fit into the project perfectly and then update the GitHub code when a release is ready, over live-updating/pulling into the GitHub code. It just makes it way easier for me to handle changes, especially if there are sudden changes on Googles end and i end up with code where i know exactly what causes a given problem in the end (:

**Comment by ELowry** [comment]
Ah, gotcha!

I had figured the css was being replaced and not just added on, so I didn't think it would be an issue.

Might I suggest adding an ID or class to the injected css and using that to replace it instead of adding a new one in? I'll send over an updated version of the function you use that includes this if you want. It should reduce the risk of this sort of issue and probably keep the page cleaner.

As for changing the grid size vs the item size, I guess that makes sense. The main reason I was going for this was to try and keep things "aligned" with how Stadia is set up, but I agree that your way of doing things is probably more robust.

**Comment by ChristopherKlay** [comment]
> Might I suggest adding an ID or class to the injected css and using that to replace it instead of adding a new one in?

I actually already thought about that, but it's a bit complicated to implement.

I'm currently working on changing the global style function to simply take a class name as a argument and replace the current element whenever one exists, to solve that. It doesn't create issues or performance loss currently, it just looks bad when inspecting it. It will be changed together with a couple of other performance improvements in a future update however (:

**Comment by ELowry** [comment]
Great minds think alike #61 =)

I hadn't though that replacing it might temporarily glitch out the styling. A solution for that would be to have 2 of them and sort of jump back & forth (clearing the content of the other one after a short delay).

**Pull request closed without merging**
