### PR TITLE
StadiaIcons Shortcuts Integration

### PR DESCRIPTION
**Pull request by ELowry**
Hi there!

I started playing around with your plugin and went and added a button to the top-right of each library item that opens up a [StadiaIcons Shortcuts](https://github.com/ELowry/StadiaIcons/tree/master/Shortcuts) window.

This setting has 3 modes (which I'll let you rename if you see fit):
1.  Auto-hide, which only shows the icon when the game item is hovered over or focused on (controller).
2. Shortcuts, which displays the icon all the time.
3. Hidden, which hides the icon.

Note: I had to split out the construction of the `enhanced_wrapper` object so that it could then be used by both the game filtering and shortcuts system. This now gives you access to a list with an `object` (`enhanced_wrappers`) for each per game that follows this structure:
```javascript
{
    parent: 'DOM object', // The parent structure of the games list
    id: 'string', // The game's uid
    name: 'string', // The title of the game
    wrapper: 'DOM object', // The enhanced_wrapper object for this game
    game: 'DOM object', // The original Stadia game list object
    visibility: 'DOM object', // The visibility toggle button for this game
    shortcut: 'DOM object' // The shortcut button/link for this object
}

### CODE REVIEW

**Comment by ChristopherKlay** [comment]
One slight issue here; The shortcut you open isn't actually the game you click on currently. It's the first game on the homescreen 😛

**Comment by ELowry** [comment]
This should actually be fixed with the last small fix I pushed =)

**Comment by ChristopherKlay** [comment]
Yea, i just noticed that - my bad!

Currently testing some things (mainly due to me making changes on the dev version that isn't live), but i'm pretty confident i can just merge this in. (:

**Comment by ChristopherKlay** [comment]
Update: If you are fine with it, i'll merge this into the current version, update the translation page / topics and then push it as part of v1.7.0 to the store, together with a couple of things from my side in a day or two (as soon as the translations are in and such). (:

**Comment by ELowry** [comment]
Perfect!

**Pull request merged**
